"""empty message

Revision ID: 441fbf0f51f1
Revises: 9988c4c54674
Create Date: 2023-07-29 09:19:56.780175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '441fbf0f51f1'
down_revision = '9988c4c54674'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estimations_summaries',
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('leakage_index', sa.Integer(), nullable=False),
    sa.Column('simulation_detection_rate_ids', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_estimations_summaries'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estimations_summaries')
    # ### end Alembic commands ###
