"""empty message

Revision ID: 51dc428de464
Revises: b4b5c30d4797
Create Date: 2023-07-29 20:42:44.586302

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '51dc428de464'
down_revision = 'b4b5c30d4797'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
