"""empty message

Revision ID: 772382a319cb
Revises: ae05fee9dd2f
Create Date: 2023-07-23 18:57:42.441842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '772382a319cb'
down_revision = 'ae05fee9dd2f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_detection_rates',
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('anomaly_detection_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anomaly_detection_id'], ['anomaly_detections.id'], name=op.f('fk_simulation_detection_rates_anomaly_detection_id_anomaly_detections')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_simulation_detection_rates'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulation_detection_rates')
    # ### end Alembic commands ###
