"""empty message

Revision ID: ae05fee9dd2f
Revises: fd61eb071b42
Create Date: 2023-07-19 10:05:14.735294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae05fee9dd2f'
down_revision = 'fd61eb071b42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('z_roof', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'z_roof')
    # ### end Alembic commands ###
