"""empty message

Revision ID: c160adb07d59
Revises: 772382a319cb
Create Date: 2023-07-23 19:12:17.019823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c160adb07d59'
down_revision = '772382a319cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulation_detection_rates', sa.Column('leakage', sa.JSON(), nullable=False))
    op.add_column('simulation_detection_rates', sa.Column('concentrations', sa.String(), nullable=False))
    op.drop_column('simulation_detection_rates', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulation_detection_rates', sa.Column('value', sa.VARCHAR(), nullable=False))
    op.drop_column('simulation_detection_rates', 'concentrations')
    op.drop_column('simulation_detection_rates', 'leakage')
    # ### end Alembic commands ###
