### Create a new sensor and its configuration
POST {{HTTP__BASE_URL}}/templates/1/sensors
Content-Type: application/json

{
    "name": "trestakk",
    "x": 1.0,
    "y": 1.0,
    "z": 1.0 
}



### Get the list of all sensors within the template
GET {{HTTP__BASE_URL}}/templates/1/sensors



### Get the filtered list of sensors
GET {{HTTP__BASE_URL}}/sensors?pinned=false



### Retrieve the sensor with its configuration
GET {{HTTP__BASE_URL}}/sensors/1



### Update partially
PATCH {{HTTP__BASE_URL}}/sensors/1
Content-Type: application/json

{

    "x": 2,
    "y": 3

}



### Delete sensor and its configuration
DELETE {{HTTP__BASE_URL}}/sensors/1



### Interactive feedback mode toggle
PATCH {{HTTP__BASE_URL}}/sensors/1/interactive-feedback-mode/toggle



### Toggle the pin status
PATCH {{HTTP__BASE_URL}}/sensors/1/pin/toggle
