### Create a new sensor
POST {{HTTP__BASE_URL}}/templates/1/sensors
Content-Type: application/json

{
    "name": "18AIL012A",
    "x": 12.2,
    "y": 13.2,
    "z": 14.2
}


### Get the list of all sensors within the template
GET {{HTTP__BASE_URL}}/templates/1/sensors


### Retrieve the sensor
GET {{HTTP__BASE_URL}}/sensors/1
